### ISSUE TITLE
design new issue page

### ISSUE THREAD

**Issue by CodeWithBishal** [OWASP-BLT/BLT#1627]
Proposing this design for the bug description page.

<img width="826" alt="Screenshot 2024-03-06 at 9 41 12 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/eb1653f1-18c0-46a7-ae43-8f49b33d95ea">

Here is a summary of each significant piece of information and functionality included in the page:

- [x] Title and Open Graph Tags: The page's title and Open Graph metadata are dynamically set to include the domain title and the bug description, enhancing SEO and shareability on social media platforms.

- [x] Bug Description and Metadata: Displays the bug description, view count, and other metadata such as domain URL, allowing users to understand the bug context. It includes actions like copying the title, sharing on social media, and bookmarking.

- [ ] Translation Feature: Incorporates Google Translate to enable translating the page content, improving accessibility for non-English speakers.

- [x] Reporter and Domain Information: Shows details about the bug's reporter (with a link to their profile) and the affected domain, including the number of issues reported and options to subscribe to bug notifications for the domain.

- [x] Browser and OS Information: Presents the browser version, operating system, and OS version used when the bug was reported, which can be crucial for debugging.

- [x] Bug Type, Status, and Management: Displays the bug's type and current status (open or closed), with options for authorized users to edit the issue, change its status, or delete it. A feature for reporting the issue anonymously is also provided.

- [ ] GitHub Integration: Offers links to view the bug on GitHub or to report it there, enhancing collaboration and tracking.

- [x] Description and Screenshots: A section for a more detailed description of the bug using Markdown, rendered into HTML, and a display of associated screenshots to visually represent the bug.

- [ ] OCR Results: If available, shows the results of Optical Character Recognition on the bug's screenshots, aiding in understanding text within images.

- [x] Comments Section: Allows users to view existing comments and add their own, fostering community discussion and collaboration on bug resolution.

- [x] Interactive Scripts: Includes JavaScript to handle various interactions on the page, such as editing the bug report, updating the issue status, liking/disliking, flagging/unflagging, and bookmarking issues. It also contains functionality for sanitizing URLs and integrating Markdown descriptions with embedded images.

TODO:
Remove:
files inside remove folder
and 

```
urls.py
Remove: IssueView
re_path(r"^like_issue/(?P<issue_pk>\d+)/$", website.views.like_issue, name="like_issue"),
    re_path(
        r"^dislike_issue/(?P<issue_pk>\d+)/$",
        website.views.dislike_issue,
        name="dislike_issue",
    ),
    re_path(r"^flag_issue/(?P<issue_pk>\d+)/$", website.views.flag_issue, name="flag_issue"),
    re_path(r"^like_issue2/(?P<issue_pk>\d+)/$", like_issue2, name="like_issue2"),
    re_path(r"^dislike_issue2/(?P<issue_pk>\d+)/$", dislike_issue2, name="dislike_issue2"),
    re_path(r"^flag_issue2/(?P<issue_pk>\d+)/$", flag_issue2, name="flag_issue2"),
    re_path(r"^issue/(?P<slug>\w+)/$", IssueView.as_view(), name="issue_view"),
    re_path(r"^issue2/(?P<slug>\w+)/$", IssueView2.as_view(), name="issue_view2"),

views.py
Remove
like_issue2, like_issue,dislike_issue,dislike_issue2,flag_issue2,flag_issue

FOLDER FILES(Remove)
includes/_likes2.html
includes/_dislike2.html
includes/_flags2.html
includes/_bookmark2.html
```

**Comment by DonnieBLT** [comment]
This is a great improvement.  I feel like it could be combined a bit more there is a lot of information to display and could use some combining of parts and separation of parts. Looks better than what we have though. Thank you!

**Comment by MattSilverio** [comment]
Hey guys, do you need some effort to these front end tasks? 

@CodeWithBishal , I felt the size of the words on the sidebar could be smaller. They are looking to me some <h2> or <h3> default size tag

Try to make like "EXPERIMENTAL" and "MORE" but keeping the black color. If not ok, try some 2-4px plus to font-size

**Comment by DhananjayDogne** [comment]
I want to work on frontend part of this enhancement .Please tell me if you need any help.
@CodeWithBishal

**Comment by CodeWithBishal** [comment]
Hi @DhananjayDogne,
Sure here is the figma file: https://www.figma.com/file/3hr4L0140ZjJpzWnPgYbip/BLT-Website?type=design&node-id=0%3A1&mode=design&t=gXz2W9lLeBYUPtit-1

Do not make changes to the "DO NOT EDIT" group. I have created a clone under "Make adjustments" Feel free to make changes here.

**Comment by aakash2330** [comment]
if the frontend for this ready @CodeWithBishal , or can I work on it ?

**Comment by CodeWithBishal** [comment]
@aakash2330 you can work on it!

**Comment by CodeWithBishal** [comment]
Hi @DonnieBLT,

I am proposing this for the final design of the Bug Description page. Do you have something to add?

<img width="881" alt="Screenshot 2024-01-18 at 7 02 59 PM" src="https://github.com/OWASP/BLT/assets/69814108/39457e2a-0d7d-4bba-bc65-f89948537171">

**Comment by DonnieBLT** [comment]
quick feedback: the title can get long so it may be good to have it on it's own line - also would like to see the CVE number, a small chart for views, and the company name bigger, along with their contact email - looks great though

**Comment by DonnieBLT** [comment]
@CodeWithBishal can you share a link to an editable figma file we can collaborate on?

**Comment by CodeWithBishal** [comment]
> @CodeWithBishal can you share a link to an editable figma file we can collaborate on?

Sure, Here is the link: https://www.figma.com/file/3hr4L0140ZjJpzWnPgYbip/BLT-Website?type=design&node-id=0%3A1&mode=design&t=TLtLWeIOVvtainZl-1

**Comment by DonnieBLT** [comment]
We lost some functionality after the recent update - lets add this back - 
![image](https://github.com/OWASP/BLT/assets/128622481/86226a04-52e4-42c8-8c39-780b9db9b211)

**Comment by CodeWithBishal** [comment]
Hi, I have tested locally and it works for me.

<img width="526" alt="Screenshot 2024-01-28 at 2 20 16 AM" src="https://github.com/OWASP/BLT/assets/69814108/8c03f6f2-6672-43dc-8b1d-add3dd71e7b2">

**Comment by DonnieBLT** [comment]
I mean to have that in the new design

**Comment by CodeWithBishal** [comment]
I have added Edit button, View on Github, Delete.

- I think it is okay if the full link is not viewable, but yes the full title should be viewable, so we need shift the 5 containers below and create 2 lines of space for title, 1 line for link(width: half line then use ellipses ... )


<img width="784" alt="Screenshot 2024-01-29 at 1 28 46 PM" src="https://github.com/OWASP/BLT/assets/69814108/d44a8eed-8136-4b0f-9640-2581772c7994">

**Comment by DonnieBLT** [comment]
Looking better. I would like each button to show the text of what it is and I think a right column with the info might be good. Can you please also add the CVE, like / dislike and suggested tip amount? You could also make the company logo bigger like the user avatar.

**Comment by CodeWithBishal** [comment]
Hi @DonnieBLT, can you please elaborate on "a right column with the info" are we talking about Popovers? 
Popovers Reference: https://getbootstrap.com/docs/5.3/components/popovers/
or
I have added text after Icon

<img width="477" alt="Screenshot 2024-01-31 at 11 29 23 PM" src="https://github.com/OWASP/BLT/assets/69814108/814f6dcb-1558-40f0-b0d1-2331d1c08bea">



> You could also make the company logo bigger like the user avatar.

Is it ok if I make the changes while implementing? right now I am using an image for the header so can't specifically alter the logo size.

> Can you please also add the CVE

I could not find CVE in the current design, could you elaborate on how should it look like and what are other components to be added on that card?

> like / dislike

Based on the CVE card design I will add this

> suggested tip amount

<img width="523" alt="Screenshot 2024-01-31 at 11 28 41 PM" src="https://github.com/OWASP/BLT/assets/69814108/a708d78c-d56c-4fc6-af43-616b262828f2">

**Comment by CodeWithBishal** [comment]
Hey @DonnieBLT ! Can I get some update on this?
Please confirm: PRs created on this issue are eligible for GSOC Leaderboard?

**Comment by DonnieBLT** [comment]
yes of course they are eligible - all of the proposed changes look good, would like to see this update.

**Comment by DonnieBLT** [comment]
I need to go through this and come up with a mockup

**Comment by CodeWithBishal** [comment]
@DonnieBLT Link to current mockup: https://www.figma.com/file/3hr4L0140ZjJpzWnPgYbip/BLT-Website?type=design&node-id=0%3A1&mode=design&t=TLtLWeIOVvtainZl-1

**Comment by CodeWithBishal** [comment]
Alright got it thanks!

**Comment by CodeWithBishal** [comment]
@DonnieBLT having some problem converting these tasks to `issues` kindly convert these tasks to issues.
