### ISSUE TITLE
Create a link on every page that says "Edit in Github"

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#1884]
Also in the meta section of the page link to the figma file. see #file-descriptions.csv

**Comment by Sarthak5598** [comment]
@DonnieBLT Do you want the edit in Github button to take us to our main Github page or do you want it to go to the html file of that webpage?

**Comment by Sarthak5598** [comment]
![image](https://github.com/OWASP-BLT/BLT/assets/108613416/34dcca3c-f96b-4ea9-8381-0d9d68f759b0)
![Screenshot 2024-03-03 111156](https://github.com/OWASP-BLT/BLT/assets/108613416/5848e0ab-0f56-43ca-90af-32a230293470)
what do you think? @DonnieBLT

**Comment by Sarthak5598** [comment]
okay !!

**Comment by Sarthak5598** [comment]
Please Close this issue after merging my PR
