### ISSUE TITLE
Review existing designs from the web platform.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2264]

**Comment by Uttkarsh-raj** [comment]
This is already done and i have reviewed the designs from the web and the figma file... 
Link: https://www.figma.com/design/qYLBM24E5Y2pyR0Dsr0FkT/Bug-Logging-Tool-(with-dark-theme)-(Copy)?node-id=0-1&t=hr4OJtyNWlqWjkM9-1
