### ISSUE TITLE
Create UI mockups in Figma or other design tools.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2265]

**Comment by Uttkarsh-raj** [comment]
Created a UI mockup using Figma and go tit reviewed by the mentors.
Link: https://www.figma.com/design/qYLBM24E5Y2pyR0Dsr0FkT/Bug-Logging-Tool-(with-dark-theme)-(Copy)?node-id=0-1&t=hr4OJtyNWlqWjkM9-1
