### ISSUE TITLE
Finalize designs and flows after mentor review.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2266]

**Comment by Uttkarsh-raj** [comment]
Finalized design, Although there are some changes that may be made along the development workflow.
https://www.figma.com/design/qYLBM24E5Y2pyR0Dsr0FkT/Bug-Logging-Tool-(with-dark-theme)-(Copy)?node-id=0-1&t=hr4OJtyNWlqWjkM9-1
