### ISSUE TITLE
Create wireframes using Figma and finalize the new design.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2284]

**Comment by CodeWithBishal** [comment]
the figma design for this page can be found at this page: https://www.figma.com/design/3hr4L0140ZjJpzWnPgYbip/BLT-Website?node-id=0-1&t=dAbqWX96C2vwNpD4-0



<img width="639" alt="Screenshot 2024-06-29 at 2 53 31 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/84e4fc67-5257-415d-976d-b90f7af2c8f1">
