### ISSUE TITLE
Issue Page Redesign: Revamp design to better organize features.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2291]

**Comment by thedudeontitan** [comment]
https://github.com/OWASP-BLT/BLT/pull/2355 This PR solves this issue.

Collaborated with @CodeWithBishal on this PR.

**Comment by thedudeontitan** [comment]
Hey @DonnieBLT, The work and PR related to this issue is merged. Should we close this issue?
