### ISSUE TITLE
Smart Contract Development: Create contracts to handle deposits, withdrawals, and payouts.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2294]

**Comment by thedudeontitan** [comment]
https://github.com/OWASP-BLT/BLT-Bounty

This is the repository with the hardhat environment with smart contract, tests and deployment script.

**Comment by thedudeontitan** [comment]
https://github.com/OWASP-BLT/BLT-Bounty/commit/2b2338ce3986db7de851cc6b9595a69c70595fdd

Hardhat project setup and created BugBounty Smart Contract
