### ISSUE TITLE
Identify where scroll-based pagination should be implemented.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2309]

**Comment by CodeWithBishal** [comment]
Scroll based pagination should be implemented in the new homepage of BLT.

## Why ?

Through scroll based pagination we will only fetch a small set of issues when user launches the home page and eventually load more data as the user scroll, which will eventually help in loading the page faster and reduce wastage of precious server resources

## How ?

As User reaches the end of page hit an api with the next page number, the api in response will send the next few issues in form of cards and using javascript we will set those cards inside the html.
