### ISSUE TITLE
Implement the scoreboard UI in Flutter and integrate with APIs.

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2316]

**Comment by Uttkarsh-raj** [comment]
This issue is solved in 2 parts .
- Creating the apis for the leaderboard - https://github.com/OWASP-BLT/BLT/pull/2123
- Implementing the leaderboard in the flutter application  - https://github.com/OWASP-BLT/BLT-Flutter/pull/406
