### ISSUE TITLE
Fix assign action (BLT-action)

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2435]

**Comment by nikhil25803** [comment]
I want to work on this issue, hence checked the logs why it is failing and found the error mentioning 
```
/home/runner/work/_actions/OWASP-BLT/BLT-Action/main/src/index.js:123
                            const issueDetails = await octokit.issues.get({
                                                 ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
```

So in the [BLT Action Repo](https://github.com/OWASP-BLT/BLT-Action), making changes accordingly will fix the issue.
Can you please assign it to me?

**Comment by arkid15r** [comment]
Fixed by https://github.com/OWASP-BLT/BLT-Action/pull/31
