### ISSUE TITLE
Refactor / rename companies to organizations

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT#2534]
Yes, renaming "Companies" to "Organizations" could make sense, especially if the entities you're referring to aren't strictly for-profit businesses or if you're including a broader range of entities like non-profits, government bodies, or other types of groups. 

**Benefits of Using "Organizations":**
- **Inclusive Terminology**: It’s more inclusive and can refer to any structured group of people, not just commercial enterprises.
- **Clarity**: If the platform caters to a diverse set of users, "Organizations" provides a clearer understanding that the platform is not limited to companies alone.
- **Flexibility**: It allows for future expansion of the platform’s scope without needing to rebrand or change terminology again.

If your platform is meant to serve a variety of entity types, "Organizations" would likely be a better fit.

**Comment by JisanAR03** [comment]
@DonnieBLT , is this okay if I make changes? in frontend only

**Comment by JisanAR03** [comment]
> There are a few more places like the menu bar and some templates that mention Companies, we can also remove the teams link in the menubar

ok I will check it our and will update

**Comment by JisanAR03** [comment]
@DonnieBLT , maybe it's ready to close
