### ISSUE TITLE
Create an Ideas & Suggestions page with voting 

### ISSUE THREAD

**Issue by fredfalcon** [OWASP-BLT/BLT#582]
integrate an idea / suggestion feature

This will allow  BLT to not only accept bugs, but feature requests to help improve the website or app

https://pypi.org/project/django-voice/

![image](https://user-images.githubusercontent.com/7475382/87330275-5aad3d80-c506-11ea-89ae-84573e5c03e9.png)

**Comment by Sarthak5598** [comment]
![BLT - Opera 23-02-2024 15_06_52](https://github.com/OWASP/BLT/assets/108613416/43b24cbd-18b8-4f03-9d02-5c525c9a870d)

![Slack - project-blt - OWASP - Opera 23-02-2024 13_50_02](https://github.com/OWASP/BLT/assets/108613416/e92f7a5a-3301-4125-a40e-441d22c79ce8)

@DonnieBLT as you suggested I Linked the suggestion page with github , I made a pull request , If you want me to make any changes please let me know!!
