### ISSUE TITLE
Create a link to each figma frame on every web page of the site, encourage new and improved designs

### ISSUE THREAD

**Issue by fredfalcon** [OWASP-BLT/BLT#810]
### Discussed in https://github.com/OWASP/BLT/discussions/695

<div type='discussions-op-text'>

<sup>Originally posted by **fredfalcon** March 29, 2021</sup>
We'd like to get all of the pages for web and mobile into the Figma design</div>

**Comment by fredfalcon** [comment]
assign to me

**Comment by juhiechandra** [comment]
I am willing to work on this issue. Please assign this issue to me. /assign

**Comment by juhiechandra** [comment]
Here are the basic layouts created for review and to get first feedback from mentors:

<img width="1512" alt="MacBook Pro 14_ - 1" src="https://user-images.githubusercontent.com/75068056/226196004-0fbfcb35-f418-4cd6-a8a4-651b0161f4b2.png">
<img width="1512" alt="MacBook Pro 14_ - 3" src="https://user-images.githubusercontent.com/75068056/226196012-40c24c64-9665-4ccd-9afa-b416f663628e.png">

**Comment by subhro1530** [comment]
Embarking on the task of linking Figma frames across OWASP's website, thereby enhancing design accessibility and collaboration. Kindly assign me this responsibility to further optimize our design process. Committed to delivering impactful contributions!

**Comment by DonnieBLT** [comment]
You can type "/ assign" (one word)
